In [5]:
import numpy as np

X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print (X)

m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m) / std)
print(X_norm)


[[  7.31546432  -2.08333096   1.03244143 ...  -6.38495873  17.67629649
    0.11084769]
 [ 12.30269233 -12.1115722   -1.38952165 ...   5.36472958  -0.2867776
   -2.24983642]
 [  7.58462898   1.73354013  -8.14243292 ...   5.13939358  -2.83042748
   -8.97255596]
 ...
 [-18.83660609  -1.71638325   1.52925104 ... -10.81879421  -3.52890762
   10.64352273]
 [  5.56766511  -0.02283569  -5.2772981  ...  -1.09840873 -14.50743229
  -12.22678853]
 [  3.94743809  -2.26243826   2.19010878 ...  -8.15583884 -12.19875896
   -0.18842209]]
[[ 0.62058065 -0.30163373  0.01021081 ... -0.70351673  1.71411964
  -0.08308215]
 [ 1.12326761 -1.32087042 -0.22804254 ...  0.51086411 -0.10377715
  -0.31226512]
 [ 0.64771107  0.0863002  -0.89233995 ...  0.48757467 -0.36119929
  -0.96492881]
 ...
 [-2.01541369 -0.2643384   0.05908297 ... -1.16177271 -0.43188679
   0.93946453]
 [ 0.44441147 -0.09221193 -0.6104909  ... -0.15712904 -1.54293408
  -1.2808604 ]
 [ 0.28110091 -0.31983759  0.12409287 ... -0.88654481 -1.309292

In [9]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [11]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
