In [1]:
import numpy as np

X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print (X)

m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m) / std)
print(X_norm)

[[ 20.03034598  -6.83945029  -5.11603146 ...  16.74495709  -8.28592255
  -22.66921341]
 [ 15.87875857   6.85242871  -7.77583859 ... -16.5226424   -1.92543932
   12.80468115]
 [  2.31316394   9.44005196  -5.7231311  ...   7.64504339   8.44332913
   -1.49410705]
 ...
 [  5.38994145  27.49689729  14.03743167 ...   4.0855343    0.23838902
    5.15559441]
 [ -0.61978613   0.85424849   5.59078709 ...   7.87696966   3.99791326
   12.10932244]
 [ -5.69407316  11.52869041  -5.31167826 ...  17.09533099   4.33083599
   -3.22879153]]
[[ 1.78460964 -0.86300742 -0.65139298 ...  1.51460097 -0.90872381
  -2.38754295]
 [ 1.38167171  0.50707481 -0.91541845 ... -1.73902111 -0.26950875
   1.22346761]
 [ 0.06504457  0.76600615 -0.71165666 ...  0.6246155   0.77253048
  -0.23205555]
 ...
 [ 0.36366537  2.57287012  1.24987347 ...  0.27649007 -0.05204859
   0.44484059]
 [-0.21961687 -0.093135    0.41141821 ...  0.64729824  0.32577562
   1.15268464]
 [-0.71210866  0.97500642 -0.67081384 ...  1.54886807  0.35923

In [2]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [3]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
